spring:
  application:
    name: bootcamp
  data:
    mongodb:
      uri:
  servlet:
    multipart:
      max-file-size: 100MB # Adjust this to the desired maximum file size
      max-request-size: 100MB # Adjust this to the desired maximum request size
  cloud:
    aws:
      credentials:
        accessKey:
        secretKey:
      region:
        static: ap-south-1
      stack:
        auto: false

server:
  port: 9098
